<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MobilityAndTransferRisk extends Model
{
    use HasFactory;

    protected $fillable = [
        'inside_independent',
        'inside_super_visad',
        'inside_carer_1',
        'inside_carer_2',
        'inside_equipment',
        'inside_fear',
        'inside_pain',
        'outside_independent',
        'outside_super_visad',
        'outside_carer_1',
        'outside_carer_2',
        'outside_equipment',
        'outside_fear',
        'outside_pain',
        'outside_risk',
        'out_bed_independent',
        'out_bed_super_visad',
        'out_bed_carer_1',
        'out_bed_carer_2',
        'out_bed_equipment',
        'out_bed_fear',
        'out_bed_pain',
        'out_bed_risk',
        'inside_risk',
        'moving_independent',
        'moving_super_visad',
        'moving_carer_1',
        'moving_carer_2',
        'moving_equipment',
        'moving_fear',
        'moving_pain',
        'moving_risk',
        'toilet_independent',
        'toilet_super_visad',
        'toilet_carer_1',
        'toilet_carer_2',
        'toilet_equipment',
        'toilet_fear',
        'toilet_pain',
        'toilet_risk',
        'transfer_independent',
        'transfer_super_visad',
        'transfer_carer_1',
        'transfer_carer_2',
        'transfer_equipment',
        'transfer_fear',
        'transfer_pain',
        'transfer_risk',
        'stand_independent',
        'stand_super_visad',
        'stand_carer_1',
        'stand_carer_2',
        'stand_equipment',
        'stand_fear',
        'stand_pain',
        'stand_risk',
        'bathing_independent',
        'bathing_super_visad',
        'bathing_carer_1',
        'bathing_carer_2',
        'bathing_equipment',
        'bathing_fear',
        'bathing_pain',
        'bathing_risk',
        'stair_independent',
        'stair_super_visad',
        'stair_carer_1',
        'stair_carer_2',
        'stair_equipment',
        'stair_fear',
        'stair_pain',
        'stair_risk',
        'emergency_independent',
        'emergency_super_visad',
        'emergency_carer_1',
        'emergency_carer_2',
        'emergency_equipment',
        'emergency_fear',
        'emergency_pain',
        'emergency_risk',
        'physical_problem',
        'communication',
        'behaviour',
        'safe_transfer_details',
        'patient_id',
        'image',
        'risk_level'
    ];

    public function patient() {
        return $this->belongsTo(Patient::class, 'patient_id');
    }
}
